DROP DATABASE IF EXISTS GOCOURSE;

CREATE DATABASE IF NOT EXISTS GOCOURSE;

USE GOCOURSE;

-- ---------------------------------------------------------------------
#	系统参数
-- ---------------------------------------------------------------------

-- TB_Data_Dictionary 数据字典
DROP TABLE IF EXISTS TB_Data_Dict;
CREATE TABLE IF NOT EXISTS TB_Data_Dict(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	TYPE_CODE VARCHAR(50) NOT NULL,
	TYPE_VALUE VARCHAR(50) NOT NULL,
	VALUE_NAME NVARCHAR(50) NOT NULL,
	DESCRIPTION NVARCHAR(200) NOT NULL
);

-- ---------------------------------------------------------------------
#	单位管理
-- ---------------------------------------------------------------------

-- TB_University 学校信息
CREATE TABLE IF NOT EXISTS TB_University (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	uni_name NVARCHAR(50) NOT NULL UNIQUE,	
	nickname NVARCHAR(30)
);

-- TB_Department 院系信息
CREATE TABLE IF NOT EXISTS TB_Department (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,	
	dept_name NVARCHAR(50) NOT NULL,
	nickname NVARCHAR(30),
	uni_id INT UNSIGNED,
	FOREIGN KEY(UNI_ID) REFERENCES TB_UNIVERSITY(ID)
);

-- TB_Class 班级信息
CREATE TABLE IF NOT EXISTS TB_Class (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	class_name NVARCHAR(50) NOT NULL,
	dept_id INT UNSIGNED,
	FOREIGN KEY(DEPT_ID) REFERENCES TB_Department(ID)
);

-- TB_Class_Hour
CREATE TABLE IF NOT EXISTS TB_Class_Hour (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,	
	UNI_ID INT UNSIGNED,
	FOREIGN KEY(UNI_ID) REFERENCES TB_UNIVERSITY(ID),
	sequence TINYINT NOT NULL,
	STARTIME TIME NOT NULL,
	ENDTIME TIME NOT NULL
);

-- ---------------------------------------------------------------------
#	用户
-- ---------------------------------------------------------------------

-- TB_USER
DROP TABLE IF EXISTS TB_USER;
CREATE TABLE IF NOT EXISTS TB_USER(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(20) NOT NULL
);

-- TB_STUDENT
DROP TABLE IF EXISTS TB_STUDENT;
CREATE TABLE IF NOT EXISTS TB_STUDENT(
	STU_ID INT UNSIGNED PRIMARY KEY,
	FOREIGN KEY(STU_ID) REFERENCES TB_USER(ID),
	CLASS_ID INT UNSIGNED NOT NULL,
	FOREIGN KEY(CLASS_ID) REFERENCES TB_Class(ID),
	REAL_NAME NVARCHAR(30) NOT NULL,
	Admission_Date DATE
);

-- TB_TEACHER
DROP TABLE IF EXISTS TB_TEACHER;
CREATE TABLE IF NOT EXISTS TB_TEACHER(
	TEAC_ID INT UNSIGNED PRIMARY KEY,
	FOREIGN KEY(TEAC_ID) REFERENCES TB_USER(ID),
	DEPT_ID INT UNSIGNED NOT NULL,
	FOREIGN KEY(DEPT_ID) REFERENCES TB_Department(ID),
	REAL_NAME NVARCHAR(30) NOT NULL
);

-- ---------------------------------------------------------------------
#	权限
-- ---------------------------------------------------------------------

-- TB_Role
DROP TABLE IF EXISTS TB_Role;
CREATE TABLE IF NOT EXISTS TB_Role(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ABBREVIATION VARCHAR(20) NOT NULL,
	ROLE_NAME NVARCHAR(50) NOT NULL,
	ROLE_TYPE CHAR(1) NOT NULL,
	DESCRIPTION	NVARCHAR(200)
);

-- TB_USER_ROLE
DROP TABLE IF EXISTS TB_USER_ROLE;
CREATE TABLE IF NOT EXISTS TB_USER_ROLE(
	USER_ID INT UNSIGNED NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES TB_USER(ID),
	ROLE_ID INT UNSIGNED NOT NULL,
	FOREIGN KEY(ROLE_ID) REFERENCES TB_Role(ID)
);

-- TB_Module
DROP TABLE IF EXISTS TB_Module;
CREATE TABLE IF NOT EXISTS TB_MODULE(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	PARENT_MODULE_ID INT UNSIGNED,
	FOREIGN KEY(PARENT_MODULE_ID) REFERENCES TB_Module(ID),
	ABBREVIATION VARCHAR(20) NOT NULL,
	MODULE_NAME NVARCHAR(50) NOT NULL,
	DESCRIPTION NVARCHAR(200)
);

-- TB_Function
DROP TABLE IF EXISTS TB_Function;
CREATE TABLE IF NOT EXISTS TB_Function(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	MODULE_ID INT UNSIGNED NOT NULL DEFAULT 0,
	FOREIGN KEY(MODULE_ID) REFERENCES TB_Module(ID),
	FUNC_NAME NVARCHAR(50) NOT NULL,
	URL VARCHAR(100) NOT NULL,
	DESCRIPTION NVARCHAR(200)
);

-- TB_Module_Function
DROP TABLE IF EXISTS TB_Module_Function;
CREATE TABLE IF NOT EXISTS TB_Module_Function(
	MODULE_ID INT UNSIGNED NOT NULL,
	FUNC_ID INT UNSIGNED NOT NULL,
	FOREIGN KEY(MODULE_ID) REFERENCES TB_Module(ID),
	FOREIGN KEY(FUNC_ID) REFERENCES TB_Function(ID)
);
