USE GOCOURSE;

SELECT * FROM TB_DATA_DICT;

SELECT * FROM TB_UNIVERSITY;

SELECT * FROM TB_DEPARTMENT;

SELECT * FROM TB_CLASS;

SELECT * FROM TB_CLASS_HOUR;

SELECT * FROM TB_USER;

SELECT * FROM TB_USER U
	LEFT JOIN TB_USER_ROLE UR
	ON U.ID = UR.USER_ID
	LEFT JOIN TB_ROLE R
	ON UR.ROLE_ID = R.ID
